Client Entity Type Registry Method
Fox2Code/FoxLoader pull request #21
Opened 2024-07-19 00:32 UTC by halotroop2288

A simple invoker for `EntityList.addMapping` with an ID tracker separate from the block and item registry.

2024-07-19 08:09 UTC, Fox2Code commented
Mappings are not implemented, this is not a hard requirement, but would be nice.
(Making server send mappings to client)

Also did you tested that with a client connecting to a server?
(With a mod that register a custom entity)

I assume singleplayer is fine.

2024-07-21 09:46 UTC, Fox2Code requested changes
The code you did show a deep understanding of FoxLoader

2024-07-21 09:46 UTC, Fox2Code commented on common/src/main/java/com/fox2code/foxloader/loader/packet/ServerHello.java
>              throw new RuntimeException("Client is critically out of date, please update FoxLoader");
Keep this code in mind for later

2024-07-21 09:46 UTC, Fox2Code commented on common/src/main/java/com/fox2code/foxloader/loader/packet/ServerHello.java
> +        if (inStream.available() < 2) {
Maybe a version check here too, this code look fine too

2024-07-21 09:46 UTC, Fox2Code commented on common/src/main/java/com/fox2code/foxloader/loader/packet/ServerHello.java
> +        outStream.writeShort(SERVER_HELLO_VERSION);
We should write what we except minimum packet version is supported for reading (In this case `0`)

Maybe adding a `public static final int  SERVER_HELLO_MIN_SUPPORT = 0;` ?

2024-07-21 09:48 UTC, Fox2Code commented
The DataInputStream is backed by a ByteArrayInputStream, so not reading the packet fully is fine.

This means if we add data at the end of the packet, old versions can safely ignore it.

2024-07-21 13:50 UTC, halotroop2288 commented on common/src/main/java/com/fox2code/foxloader/loader/packet/ServerHello.java
> +        outStream.writeShort(SERVER_HELLO_VERSION);
I tried to make the changes to ServerHello minimally invasive. It should be backwards compatible the way it is, as the entity type data is written to the end and it only reads the next data if it exists.

2024-07-21 13:51 UTC, halotroop2288 commented
^ My thoughts exactly.

2024-07-21 14:16 UTC, halotroop2288 commented on common/src/main/java/com/fox2code/foxloader/loader/packet/ServerHello.java
>              throw new RuntimeException("Client is critically out of date, please update FoxLoader");
This part is hard to read because of the broken English unfortunately. I'm not sure I understand what `SERVER_HELLO_VERSION_NEXT` is actually for.

I was expecting to find something like this:

```diff
public class ModLoader {
	/**
	 * V0 reads item/block registry data
	 * V1 reads item/block registry metadata
+	 * V2 reads entity type registry data
	 */
-	public static final int SERVER_HELLO_VERSION = 1;
+	public static final int SERVER_HELLO_VERSION = 2;
	/**
	 * The version of ServerHello that the client can read without issue
	 * This version must be less than or equal to SERVER_HELLO_VERSION
	 */
	SERVER_HELLO_BACKWARD_COMPATIBLE_VERSION = 0;
```

```java
	public void readData(DataInputStream inStream) throws IOException {
		final int serverHelloVersion = inStream.readUnsignedShort();
		if (serverHelloVersion <= SERVER_HELLO_BACKWARD_COMPATIBLE_VERSION) {
			// Client disconnects here because it can't read the packet.
			throw new IOException("Client is critically out of date. Please update FoxLoader.");
		}

		// ...
	}
```

But I don't know how to handle this code if it works differently.

2024-07-21 14:43 UTC, Fox2Code commented on common/src/main/java/com/fox2code/foxloader/loader/packet/ServerHello.java
> +        outStream.writeShort(SERVER_HELLO_VERSION);
It isn't for now because of how I made the packet, the second version is ti tell how backward compatible the packet is.

2024-07-21 14:48 UTC, halotroop2288 commented on common/src/main/java/com/fox2code/foxloader/loader/packet/ServerHello.java
> +        outStream.writeShort(SERVER_HELLO_VERSION);
Why would you need to send that information, except to tell the server which version of ClientHello it accepts? The ServerHello version only needs to be checked for compatibility on the client.

2024-07-22 09:34 UTC, Fox2Code commented on common/src/main/java/com/fox2code/foxloader/loader/packet/ServerHello.java
>              throw new RuntimeException("Client is critically out of date, please update FoxLoader");
We can't retroactively change older client code

2024-07-22 09:35 UTC, Fox2Code commented on common/src/main/java/com/fox2code/foxloader/loader/packet/ServerHello.java
> +        outStream.writeShort(SERVER_HELLO_VERSION);
Older FoxLoader client will except ClientHello to send 2 short if version is `1` or higher.

We cannot change older client code unless you have a time machine.

2024-07-22 12:12 UTC, halotroop2288 commented on common/src/main/java/com/fox2code/foxloader/loader/packet/ServerHello.java
> +        outStream.writeShort(SERVER_HELLO_VERSION);
??? There's nothing that needs to be changed

2024-07-22 12:47 UTC, halotroop2288 commented on common/src/main/java/com/fox2code/foxloader/loader/packet/ServerHello.java
>              throw new RuntimeException("Client is critically out of date, please update FoxLoader");
No shit. Got any helpful advice?

2024-07-22 14:58 UTC, Fox2Code requested changes
You did good

2024-07-22 14:58 UTC, Fox2Code commented on common/src/main/java/com/fox2code/foxloader/loader/packet/ServerHello.java
> +        int clientBackwardCompatibilityVersion = inStream.readUnsignedShort();
If `serverHelloVersion < 0` do not call `readUnsignedShort`, and assume packet version is `0`

2024-07-22 15:00 UTC, Fox2Code commented on common/src/main/java/com/fox2code/foxloader/loader/packet/ServerHello.java
>              throw new RuntimeException("Client is critically out of date, please update FoxLoader");
@halotroop2288 you are doing well!

2024-07-23 14:03 UTC, Fox2Code commented
Thanks for everything, I'll take it from there

2024-07-23 14:03 UTC, merged